langaue: node_js
node_js: stable

branches:
    only:
        - save

before_install:
    - npm install -g hexo-cli
    - git clone https://github.com/smduan/next.git themes/next

install:
    - npm install
    - npm install hexo-deployer-git --save
    
script:
    - mv _next_config.yml themes/next/_config.yml
    - hexo clean
    - hexo generate

after_script:
    - git config user.name "wuxiaobai24"
    - git config user.email "wuxiaobai24@foxmail.com"
    - sed -i "s/GITHUB_TOKEN/${GITHUB_TOKEN}/g" ./_config.yml
    - hexo deploy
