langaue: node_js
node_js: stable

branches:
    only:
        - save

before_install:
    - npm install -g hexo-cli
    - git clone https://github.com/xaoxuu/hexo-theme-material-x.git themes/material-x -b 1.2.7

install:
    - npm install
    - npm install hexo-deployer-git --save
    - npm i --save hexo-wordcount
    - npm i -S hexo-related-popular-posts
    - npm i -S hexo-helper-qrcode
    # - npm install hexo-math --save
    - npm install hexo-generator-feed --save
    
script:
    - mv theme_config.yml ./themes/material-x/_config.yml
    - hexo clean
    - hexo generate

after_script:
    - git config user.name "wuxiaobai24"
    - git config user.email "wuxiaobai24@foxmail.com"
    - sed -i "s/GITHUB_TOKEN/${GITHUB_TOKEN}/g" ./_config.yml
    - hexo deploy
